# coding: utf-8

# flake8: noqa
"""
    Policy Detection and Classification Service

    Policy Detection and Classification Service  # noqa: E501

    OpenAPI spec version: 0.0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.detect_by_text import DetectByText
from swagger_client.models.detect_by_url import DetectByUrl
from swagger_client.models.policy_terms import PolicyTerms
